if: branch = master and not type IN (pull_request)
dist: trusty
sudo: false
language: minimal
before_install: true
install: true
before_script: true
script:
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
- echo ${TRAVIS_BUILD_NUMBER} > version
- echo ${TRAVIS_COMMIT} >> version
- docker build  --no-cache -t fiware/service.keyrocktokenprovider .
- docker push fiware/service.keyrocktokenprovider
env:
  global:
  - secure: S5tKpzXYvlKMYNEp6f0lb0LaUp4SpRCkMv9Y3YcNAS32yAU+9qgypCXbExGvZB8xF7AyitAcx0DP4M5fFlibHUPRporKPGcVoOOdqCcAUdNc9NMpBN8C5JLkEp2vMfu/H/5Ir4xAjtLTUorOhx+7lpKFSKPZp/fsD7EvO/FMad3FtCkgWqe4UAx3Jn5g7enRGRzPQU8UsHtZa5kAwJaY4Dt42uunVLCS0OV7UZibOMney5j0c/ItWnRBabmjvmh2asdB8v1yb21RimkSumZv9kL87OAAQKOVqSm+8/VaMG3/DGqdnCX4CQ7xXsMjjWjDHobDd1pqZhMWLvSMDuUtZqRdSdd7V43lDzYJrmRV4bjid6okDX2xM6eKRqRzaFoIK4SBAhce2ug5OgrlqMGq+X2MCqMseAOt9wDwuaU7UO4SywMQVQpanLj+OiVfJ+UGp9HvMYwZ72//N7wkIFVsFkCs1I44QNO/eLVMKappqwOOcwPHeglfttY1in2wRBc0/kZjlvgYMUF5Hq7C+p9GOvVyqSW/WoDLk5lfdu+faHs1UethBsy5cD7a+UFH5RpKJfq6u3rQBPjx4eLtyw2ae/Xk0CY8v1Si8lzjQouEoOh96rXtanBtmsncpBDt8akMBHMxXUOQCxsbi6DB1XeYoj2V1XsjTsewHe92/wZAZpI=
  - secure: tDMT+YBb4OdbiRMcVpd4TvsBamoCJrXVQAK1OR8zmKsFNL8hO060Rez1am6IVQf7x+XeZn4o11Vwz/mD2lnx66PpbM9VvlTXZ2LBOcn0JfMpMuqv4UTQdEUWiUwefEA0jy9dekcPCIHHzqtX3yzvD84+Hk7arSSnnpDzdeWw98ECxq+J1TOl3OuHTNYs5IJtz1TSJ0qvd463o5YtwxdZdgeLJN60lPevSNJZ6SZac7CezQo2v59ObUlu/dNZVfXFi8cwR6oLR9Fk7EnLUarYQQxsuHgIl91/TyIhagpNzeKkSy8wNk1KpKU0kq8Ssc1OhNp5nI/wAshjTVqSlX7NzktsPe+A49qfpF4zMvEBsyuO9X8CkCfF8HDVgwGmXcgqBW+IjaXwquqmHy0SW81JCcyXl5qvar/aOzjI1cqEAq8EFWxDx1lnBcJnit0rTYsGIR6L6lK1Jcqm2RosfnGpF9pZIBJkpDvXIYhCu4SSqqb3EZr96RPFQ9gohCNVNxPx+eG/RFDvzEpT7zOWkiBsGcagk+Y1SZEkTnHMFNUi6+7+NfJLsblYY/862jb0qKk4AsCUHF/Ere3cBtr4C0FtVMwx9KWCuhDuV0JvDGV9H4Rx4IPeBeK9wXUmjnPmutZ9SFPa4CojI7yX/46wwhXuN7bcKjpRqNxOI92x3iUDfLw=
